"""
Builds PersistentDataset cache for the Kidney Tumour dataset.
Uses subprocess isolation — each volume is processed in a fresh Python
process so RAM is guaranteed to be released by the OS after each one.
This is the safest approach for machines with limited RAM.

Reads train/val splits from CSVs generated by create_splits_kidney.py.
Run create_splits_kidney.py BEFORE this script.

Usage:
    python scripts/build_cache_kidney.py
"""

import argparse
import csv
import os
import sys
import subprocess

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# ─────────────────────────────────────────────
#  SINGLE-VOLUME WORKER
#  Called in a subprocess for each volume.
#  Also the __main__ entry point when invoked as a child process.
# ─────────────────────────────────────────────
def cache_single_volume(image_path: str, label_path: str, cache_dir: str):
    """Processes and caches exactly one volume then exits."""
    import torch
    from monai.data.meta_tensor import MetaTensor
    torch.serialization.add_safe_globals([MetaTensor])
    from monai.data import PersistentDataset

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, project_root)
    #from data_loaders.dataset_kidney import get_cache_transform
    from data_loaders.dataset_kidney_transformer import get_cache_transform
    ds = PersistentDataset(
        data=[{"image": image_path, "label": label_path}],
        transform=get_cache_transform(),
        cache_dir=cache_dir,
    )
    _ = ds[0]   # triggers transform and writes to disk


# ─────────────────────────────────────────────
#  CSV LOADER
# ─────────────────────────────────────────────
def load_split_csv(csv_path: str, data_root: str) -> list:
    """
    Reads a split CSV (case_id column) and returns
    a list of {image, label} dicts with full paths resolved.
    Skips any case where files are missing on disk and warns.
    """
    kidney_dir = os.path.join(data_root, "Kidney", "data")
    files = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            case_name  = row["case_id"]
            case_dir   = os.path.join(kidney_dir, case_name)
            img_path   = os.path.join(case_dir, "imaging.nii.gz")
            label_path = os.path.join(case_dir, "segmentation.nii.gz")
            if not os.path.exists(img_path) or not os.path.exists(label_path):
                print(f"[WARN] Skipping {case_name} — file(s) missing on disk.")
                continue
            files.append({"image": img_path, "label": label_path})
    return files


# ─────────────────────────────────────────────
#  CACHE BUILD ORCHESTRATOR
# ─────────────────────────────────────────────
def run_cache_build(files: list, cache_dir: str, label: str):
    n      = len(files)
    failed = []

    for i, item in enumerate(files):
        img       = item["image"]
        lbl       = item["label"]
        case_name = os.path.basename(os.path.dirname(img))

        cmd = [
            sys.executable,
            __file__,
            "--worker",
            "--image",     img,
            "--label",     lbl,
            "--cache_dir", cache_dir,
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
        )

        status = "✓" if result.returncode == 0 else "✗ FAILED"
        print(f"  [{label}] [{i+1:03d}/{n}] {case_name}  {status}", end="\r")

        if result.returncode != 0:
            failed.append(case_name)
            print(f"\n  ERROR on {case_name}:")
            if result.stderr:
                lines = result.stderr.strip().splitlines()
                for line in lines[-5:]:
                    print(f"    {line}")

    print()   # newline after \r
    if failed:
        print(f"  ⚠ {len(failed)} volumes failed: {failed}")
    else:
        print(f"  ✅ All {n} volumes cached successfully.")


# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data_root",
        type=str,
        default=r"data",
        help="Top-level data/ folder (containing Kidney/data/case_XXXXX/)"
    )
    parser.add_argument(
        "--cache_dir",
        type=str,
        default=r"cache/kidney",
        help="Directory to store cached tensors (~50-100GB needed for 300 cases)"
    )
    parser.add_argument(
        "--split_dir",
        type=str,
        default=r"data/splits",
        help="Directory containing train_kidney.csv and val_kidney.csv"
    )

    # Internal worker flags — used when called as a subprocess
    parser.add_argument("--worker",    action="store_true", default=False)
    parser.add_argument("--image",     type=str, default=None)
    parser.add_argument("--label",     type=str, default=None)

    args = parser.parse_args()

    # ── Worker mode: process one volume and exit ──
    if args.worker:
        cache_single_volume(args.image, args.label, args.cache_dir)
        return

    # ── Orchestrator mode ──
    print("=" * 60)
    print("Building Kidney Tumour cache (subprocess-isolated, memory-safe)")
    print(f"  data_root : {args.data_root}")
    print(f"  cache_dir : {args.cache_dir}")
    print(f"  split_dir : {args.split_dir}")
    print(f"  spacing   : 1.5mm isotropic")
    print(f"  classes   : 3  (0=background, 1=kidney, 2=tumour)")
    print("=" * 60)

    train_csv = os.path.join(args.split_dir, "train_kidney.csv")
    val_csv   = os.path.join(args.split_dir, "val_kidney.csv")

    if not os.path.exists(train_csv) or not os.path.exists(val_csv):
        raise RuntimeError(
            f"Split CSVs not found in {args.split_dir}.\n"
            f"Run create_splits_kidney.py first to generate them."
        )

    train_files = load_split_csv(train_csv, args.data_root)
    val_files   = load_split_csv(val_csv,   args.data_root)

    if not train_files:
        raise RuntimeError("No valid training cases found after reading CSV.")

    print(f"\nTrain : {len(train_files)} cases  (from train_kidney.csv)")
    print(f"Val   : {len(val_files)} cases  (from val_kidney.csv)")

    train_cache = os.path.join(args.cache_dir, "kidney_train")
    val_cache   = os.path.join(args.cache_dir, "kidney_val")
    os.makedirs(train_cache, exist_ok=True)
    os.makedirs(val_cache,   exist_ok=True)

    print("\nCaching training volumes...")
    run_cache_build(train_files, train_cache, "Train")

    print("\nCaching validation volumes...")
    run_cache_build(val_files, val_cache, "Val")

    print("\n✅ Cache complete. Ready to start training.")


if __name__ == "__main__":
    main()